# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: applicationmaster_protocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import yarn_service_protos_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='applicationmaster_protocol.proto',
  package='hadoop.yarn',
  serialized_pb='\n applicationmaster_protocol.proto\x12\x0bhadoop.yarn\x1a\x19yarn_service_protos.proto2\xfc\x02\n ApplicationMasterProtocolService\x12\x84\x01\n\x19registerApplicationMaster\x12\x32.hadoop.yarn.RegisterApplicationMasterRequestProto\x1a\x33.hadoop.yarn.RegisterApplicationMasterResponseProto\x12~\n\x17\x66inishApplicationMaster\x12\x30.hadoop.yarn.FinishApplicationMasterRequestProto\x1a\x31.hadoop.yarn.FinishApplicationMasterResponseProto\x12Q\n\x08\x61llocate\x12!.hadoop.yarn.AllocateRequestProto\x1a\".hadoop.yarn.AllocateResponseProtoBB\n\x1corg.apache.hadoop.yarn.protoB\x19\x41pplicationMasterProtocol\x88\x01\x01\x90\x01\x01\xa0\x01\x01')





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\034org.apache.hadoop.yarn.protoB\031ApplicationMasterProtocol\210\001\001\220\001\001\240\001\001')

_APPLICATIONMASTERPROTOCOLSERVICE = _descriptor.ServiceDescriptor(
  name='ApplicationMasterProtocolService',
  full_name='hadoop.yarn.ApplicationMasterProtocolService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=77,
  serialized_end=457,
  methods=[
  _descriptor.MethodDescriptor(
    name='registerApplicationMaster',
    full_name='hadoop.yarn.ApplicationMasterProtocolService.registerApplicationMaster',
    index=0,
    containing_service=None,
    input_type=yarn_service_protos_pb2._REGISTERAPPLICATIONMASTERREQUESTPROTO,
    output_type=yarn_service_protos_pb2._REGISTERAPPLICATIONMASTERRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='finishApplicationMaster',
    full_name='hadoop.yarn.ApplicationMasterProtocolService.finishApplicationMaster',
    index=1,
    containing_service=None,
    input_type=yarn_service_protos_pb2._FINISHAPPLICATIONMASTERREQUESTPROTO,
    output_type=yarn_service_protos_pb2._FINISHAPPLICATIONMASTERRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='allocate',
    full_name='hadoop.yarn.ApplicationMasterProtocolService.allocate',
    index=2,
    containing_service=None,
    input_type=yarn_service_protos_pb2._ALLOCATEREQUESTPROTO,
    output_type=yarn_service_protos_pb2._ALLOCATERESPONSEPROTO,
    options=None,
  ),
])

class ApplicationMasterProtocolService(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _APPLICATIONMASTERPROTOCOLSERVICE
class ApplicationMasterProtocolService_Stub(ApplicationMasterProtocolService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _APPLICATIONMASTERPROTOCOLSERVICE

# @@protoc_insertion_point(module_scope)
