# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: application_history_client.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import Security_pb2
import yarn_service_protos_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='application_history_client.proto',
  package='hadoop.yarn',
  serialized_pb='\n application_history_client.proto\x12\x0bhadoop.yarn\x1a\x0eSecurity.proto\x1a\x19yarn_service_protos.proto2\xcd\x08\n!ApplicationHistoryProtocolService\x12u\n\x14getApplicationReport\x12-.hadoop.yarn.GetApplicationReportRequestProto\x1a..hadoop.yarn.GetApplicationReportResponseProto\x12\x66\n\x0fgetApplications\x12(.hadoop.yarn.GetApplicationsRequestProto\x1a).hadoop.yarn.GetApplicationsResponseProto\x12\x8a\x01\n\x1bgetApplicationAttemptReport\x12\x34.hadoop.yarn.GetApplicationAttemptReportRequestProto\x1a\x35.hadoop.yarn.GetApplicationAttemptReportResponseProto\x12{\n\x16getApplicationAttempts\x12/.hadoop.yarn.GetApplicationAttemptsRequestProto\x1a\x30.hadoop.yarn.GetApplicationAttemptsResponseProto\x12o\n\x12getContainerReport\x12+.hadoop.yarn.GetContainerReportRequestProto\x1a,.hadoop.yarn.GetContainerReportResponseProto\x12`\n\rgetContainers\x12&.hadoop.yarn.GetContainersRequestProto\x1a\'.hadoop.yarn.GetContainersResponseProto\x12s\n\x12getDelegationToken\x12-.hadoop.common.GetDelegationTokenRequestProto\x1a..hadoop.common.GetDelegationTokenResponseProto\x12y\n\x14renewDelegationToken\x12/.hadoop.common.RenewDelegationTokenRequestProto\x1a\x30.hadoop.common.RenewDelegationTokenResponseProto\x12|\n\x15\x63\x61ncelDelegationToken\x12\x30.hadoop.common.CancelDelegationTokenRequestProto\x1a\x31.hadoop.common.CancelDelegationTokenResponseProtoBC\n\x1corg.apache.hadoop.yarn.protoB\x1a\x41pplicationHistoryProtocol\x88\x01\x01\x90\x01\x01\xa0\x01\x01')





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\034org.apache.hadoop.yarn.protoB\032ApplicationHistoryProtocol\210\001\001\220\001\001\240\001\001')

_APPLICATIONHISTORYPROTOCOLSERVICE = _descriptor.ServiceDescriptor(
  name='ApplicationHistoryProtocolService',
  full_name='hadoop.yarn.ApplicationHistoryProtocolService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=93,
  serialized_end=1194,
  methods=[
  _descriptor.MethodDescriptor(
    name='getApplicationReport',
    full_name='hadoop.yarn.ApplicationHistoryProtocolService.getApplicationReport',
    index=0,
    containing_service=None,
    input_type=yarn_service_protos_pb2._GETAPPLICATIONREPORTREQUESTPROTO,
    output_type=yarn_service_protos_pb2._GETAPPLICATIONREPORTRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getApplications',
    full_name='hadoop.yarn.ApplicationHistoryProtocolService.getApplications',
    index=1,
    containing_service=None,
    input_type=yarn_service_protos_pb2._GETAPPLICATIONSREQUESTPROTO,
    output_type=yarn_service_protos_pb2._GETAPPLICATIONSRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getApplicationAttemptReport',
    full_name='hadoop.yarn.ApplicationHistoryProtocolService.getApplicationAttemptReport',
    index=2,
    containing_service=None,
    input_type=yarn_service_protos_pb2._GETAPPLICATIONATTEMPTREPORTREQUESTPROTO,
    output_type=yarn_service_protos_pb2._GETAPPLICATIONATTEMPTREPORTRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getApplicationAttempts',
    full_name='hadoop.yarn.ApplicationHistoryProtocolService.getApplicationAttempts',
    index=3,
    containing_service=None,
    input_type=yarn_service_protos_pb2._GETAPPLICATIONATTEMPTSREQUESTPROTO,
    output_type=yarn_service_protos_pb2._GETAPPLICATIONATTEMPTSRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getContainerReport',
    full_name='hadoop.yarn.ApplicationHistoryProtocolService.getContainerReport',
    index=4,
    containing_service=None,
    input_type=yarn_service_protos_pb2._GETCONTAINERREPORTREQUESTPROTO,
    output_type=yarn_service_protos_pb2._GETCONTAINERREPORTRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getContainers',
    full_name='hadoop.yarn.ApplicationHistoryProtocolService.getContainers',
    index=5,
    containing_service=None,
    input_type=yarn_service_protos_pb2._GETCONTAINERSREQUESTPROTO,
    output_type=yarn_service_protos_pb2._GETCONTAINERSRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getDelegationToken',
    full_name='hadoop.yarn.ApplicationHistoryProtocolService.getDelegationToken',
    index=6,
    containing_service=None,
    input_type=Security_pb2._GETDELEGATIONTOKENREQUESTPROTO,
    output_type=Security_pb2._GETDELEGATIONTOKENRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='renewDelegationToken',
    full_name='hadoop.yarn.ApplicationHistoryProtocolService.renewDelegationToken',
    index=7,
    containing_service=None,
    input_type=Security_pb2._RENEWDELEGATIONTOKENREQUESTPROTO,
    output_type=Security_pb2._RENEWDELEGATIONTOKENRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='cancelDelegationToken',
    full_name='hadoop.yarn.ApplicationHistoryProtocolService.cancelDelegationToken',
    index=8,
    containing_service=None,
    input_type=Security_pb2._CANCELDELEGATIONTOKENREQUESTPROTO,
    output_type=Security_pb2._CANCELDELEGATIONTOKENRESPONSEPROTO,
    options=None,
  ),
])

class ApplicationHistoryProtocolService(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _APPLICATIONHISTORYPROTOCOLSERVICE
class ApplicationHistoryProtocolService_Stub(ApplicationHistoryProtocolService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _APPLICATIONHISTORYPROTOCOLSERVICE

# @@protoc_insertion_point(module_scope)
