# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resourcemanager_administration_protocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import server.yarn_server_resourcemanager_service_protos_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='resourcemanager_administration_protocol.proto',
  package='hadoop.yarn',
  serialized_pb='\n-resourcemanager_administration_protocol.proto\x12\x0bhadoop.yarn\x1a\x37server/yarn_server_resourcemanager_service_protos.proto2\xd9\x07\n,ResourceManagerAdministrationProtocolService\x12`\n\rrefreshQueues\x12&.hadoop.yarn.RefreshQueuesRequestProto\x1a\'.hadoop.yarn.RefreshQueuesResponseProto\x12]\n\x0crefreshNodes\x12%.hadoop.yarn.RefreshNodesRequestProto\x1a&.hadoop.yarn.RefreshNodesResponseProto\x12\xa2\x01\n#refreshSuperUserGroupsConfiguration\x12<.hadoop.yarn.RefreshSuperUserGroupsConfigurationRequestProto\x1a=.hadoop.yarn.RefreshSuperUserGroupsConfigurationResponseProto\x12\x8a\x01\n\x1brefreshUserToGroupsMappings\x12\x34.hadoop.yarn.RefreshUserToGroupsMappingsRequestProto\x1a\x35.hadoop.yarn.RefreshUserToGroupsMappingsResponseProto\x12i\n\x10refreshAdminAcls\x12).hadoop.yarn.RefreshAdminAclsRequestProto\x1a*.hadoop.yarn.RefreshAdminAclsResponseProto\x12o\n\x12refreshServiceAcls\x12+.hadoop.yarn.RefreshServiceAclsRequestProto\x1a,.hadoop.yarn.RefreshServiceAclsResponseProto\x12i\n\x10getGroupsForUser\x12).hadoop.yarn.GetGroupsForUserRequestProto\x1a*.hadoop.yarn.GetGroupsForUserResponseProto\x12o\n\x12updateNodeResource\x12+.hadoop.yarn.UpdateNodeResourceRequestProto\x1a,.hadoop.yarn.UpdateNodeResourceResponseProtoBN\n\x1corg.apache.hadoop.yarn.protoB%ResourceManagerAdministrationProtocol\x88\x01\x01\x90\x01\x01\xa0\x01\x01')





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\034org.apache.hadoop.yarn.protoB%ResourceManagerAdministrationProtocol\210\001\001\220\001\001\240\001\001')

_RESOURCEMANAGERADMINISTRATIONPROTOCOLSERVICE = _descriptor.ServiceDescriptor(
  name='ResourceManagerAdministrationProtocolService',
  full_name='hadoop.yarn.ResourceManagerAdministrationProtocolService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=120,
  serialized_end=1105,
  methods=[
  _descriptor.MethodDescriptor(
    name='refreshQueues',
    full_name='hadoop.yarn.ResourceManagerAdministrationProtocolService.refreshQueues',
    index=0,
    containing_service=None,
    input_type=server.yarn_server_resourcemanager_service_protos_pb2._REFRESHQUEUESREQUESTPROTO,
    output_type=server.yarn_server_resourcemanager_service_protos_pb2._REFRESHQUEUESRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='refreshNodes',
    full_name='hadoop.yarn.ResourceManagerAdministrationProtocolService.refreshNodes',
    index=1,
    containing_service=None,
    input_type=server.yarn_server_resourcemanager_service_protos_pb2._REFRESHNODESREQUESTPROTO,
    output_type=server.yarn_server_resourcemanager_service_protos_pb2._REFRESHNODESRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='refreshSuperUserGroupsConfiguration',
    full_name='hadoop.yarn.ResourceManagerAdministrationProtocolService.refreshSuperUserGroupsConfiguration',
    index=2,
    containing_service=None,
    input_type=server.yarn_server_resourcemanager_service_protos_pb2._REFRESHSUPERUSERGROUPSCONFIGURATIONREQUESTPROTO,
    output_type=server.yarn_server_resourcemanager_service_protos_pb2._REFRESHSUPERUSERGROUPSCONFIGURATIONRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='refreshUserToGroupsMappings',
    full_name='hadoop.yarn.ResourceManagerAdministrationProtocolService.refreshUserToGroupsMappings',
    index=3,
    containing_service=None,
    input_type=server.yarn_server_resourcemanager_service_protos_pb2._REFRESHUSERTOGROUPSMAPPINGSREQUESTPROTO,
    output_type=server.yarn_server_resourcemanager_service_protos_pb2._REFRESHUSERTOGROUPSMAPPINGSRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='refreshAdminAcls',
    full_name='hadoop.yarn.ResourceManagerAdministrationProtocolService.refreshAdminAcls',
    index=4,
    containing_service=None,
    input_type=server.yarn_server_resourcemanager_service_protos_pb2._REFRESHADMINACLSREQUESTPROTO,
    output_type=server.yarn_server_resourcemanager_service_protos_pb2._REFRESHADMINACLSRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='refreshServiceAcls',
    full_name='hadoop.yarn.ResourceManagerAdministrationProtocolService.refreshServiceAcls',
    index=5,
    containing_service=None,
    input_type=server.yarn_server_resourcemanager_service_protos_pb2._REFRESHSERVICEACLSREQUESTPROTO,
    output_type=server.yarn_server_resourcemanager_service_protos_pb2._REFRESHSERVICEACLSRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getGroupsForUser',
    full_name='hadoop.yarn.ResourceManagerAdministrationProtocolService.getGroupsForUser',
    index=6,
    containing_service=None,
    input_type=server.yarn_server_resourcemanager_service_protos_pb2._GETGROUPSFORUSERREQUESTPROTO,
    output_type=server.yarn_server_resourcemanager_service_protos_pb2._GETGROUPSFORUSERRESPONSEPROTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='updateNodeResource',
    full_name='hadoop.yarn.ResourceManagerAdministrationProtocolService.updateNodeResource',
    index=7,
    containing_service=None,
    input_type=server.yarn_server_resourcemanager_service_protos_pb2._UPDATENODERESOURCEREQUESTPROTO,
    output_type=server.yarn_server_resourcemanager_service_protos_pb2._UPDATENODERESOURCERESPONSEPROTO,
    options=None,
  ),
])

class ResourceManagerAdministrationProtocolService(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _RESOURCEMANAGERADMINISTRATIONPROTOCOLSERVICE
class ResourceManagerAdministrationProtocolService_Stub(ResourceManagerAdministrationProtocolService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _RESOURCEMANAGERADMINISTRATIONPROTOCOLSERVICE

# @@protoc_insertion_point(module_scope)
